image: node:16

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - .npm/

stages:
  - lint
  - test
  - build
  - coverage

before_script:
  - npm ci --cache .npm --prefer-offline

lint-frontend:
  stage: lint
  script:
    - npm run lint -w frontend

lint-backend:
  stage: lint
  script:
    - npm run lint -w backend

test-frontend:
  stage: test
  script:
    - npm run test -w frontend

test-backend:
  stage: test
  script:
    - npm run test -w backend

build-frontend:
  stage: build
  script:
    - npm run build -w frontend

build-backend:
  stage: build
  script:
    - npm run build -w backend

coverage-frontend:
  stage: coverage
  script:
    - npm run test:cov -w frontend
  coverage: '/Statements\s+:\s(\d+.?\d+)%/'

coverage-backend:
  stage: coverage
  script:
    - npm run test:cov -w backend
  coverage: '/Statements\s+:\s(\d+.?\d+)%/'
