image: node:16

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - .npm/

default:
  retry:
    max: 2
    when:
      - runner_system_failure
      - scheduler_failure
      - runner_unsupported
      - archived_failure
      - unmet_prerequisites

stages:
  - lint
  - test
  - build
  - coverage
  - analyze

before_script:
  - npm ci --cache .npm --prefer-offline

lint-frontend:
  stage: lint
  script:
    - npm run lint -w frontend

lint-backend:
  stage: lint
  script:
    - npm run lint -w backend

test-frontend:
  needs: ["lint-frontend"]
  stage: test
  script:
    - npm run test -w frontend

test-backend:
  needs: ["lint-backend"]
  stage: test
  script:
    - npm run test -w backend

e2e test-backend:
  needs: ["lint-backend"]
  stage: test
  script:
    - npm run test:e2e -w backend



# integration-test:
#   image: cypress/base:16.13.0
#   needs: ["lint-backend", "lint-frontend"]
#   stage: test
#   script:
#     - npm run cy:run

build-frontend:
  needs: ["test-frontend", "lint-frontend"]
  stage: build
  script:
    - npm run build -w frontend

build-backend:
  needs: ["test-backend", "lint-backend"]
  stage: build
  script:
    - npm run build -w backend

coverage-frontend:
  needs: ["test-frontend"]
  stage: coverage
  script:
    - npm run test:cov -w frontend
  coverage: '/Statements\s+:\s(\d+.?\d+)%/'

coverage-backend:
  needs: ["test-backend"]
  stage: coverage
  script:
    - npm run test:cov -w backend
  coverage: '/Statements\s+:\s(\d+.?\d+)%/'

mutation-backend:
  needs: ["test-backend"]
  stage: coverage
  script:
    - npm run test:mutation -w backend

sonar-scanner:
  stage: analyze
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    SONAR_TOKEN: "${SONAR_TOKEN}"
    SONAR_HOST_URL: "${SONAR_HOSTURL}"
    GIT_DEPTH: 0
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - npm run test:cov -w frontend
    - npm run test:cov -w backend
    - sonar-scanner
  allow_failure: true
  only:
    - master

