version: "3.9"
services:
  local-database:
    image: mongo:5.0.4
    environment:
      MONGO_INITDB_DATABASE: danceWithMe
    ports:
      - 27017:27017
    volumes:
      - mongodb-data-container-local:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://local-database:27017/

  local-minio-server:
    image: minio/minio:RELEASE.2022-05-19T18-20-59Z
    ports:
      - 9000:9000
    volumes:
      - minio-data-local:/data
    env_file:
      - ./local.env
    command: server /data
    labels:
      - "traefik.enable=false"
    restart: always

  local-neo4j:
    image: neo4j:4.4.6
    ports:
      - '7474:7474'
      - '7687:7687'
    volumes:
      - neo4j-data-local:/data
    env_file:
      - ./local.env
    restart: always

volumes:
  mongodb-data-container-local:
  minio-data-local:
  neo4j-data-local:
