version: "3.9"
services:
  dev-server:
    build:
      context: .
      target: development
      dockerfile: ./backend/Dockerfile
    hostname: server
    volumes:
      - ./backend:/usr/src/app/backend
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - "dev-database"
    env_file:
      - ./develop.env
      - ./secrets.env
    networks:
      - dev-internal

  dev-webclient:
    build:
      context: .
      target: development
      dockerfile: ./frontend/Dockerfile
    volumes:
      - ./frontend:/usr/src/app/frontend
      - /usr/src/app/node_modules
    ports:
      - 8080:4200
    networks:
      - dev-internal

  dev-database:
    image: mongo:5.0.4
    environment:
      MONGO_INITDB_DATABASE: danceWithMe
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - dev-internal

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://dev-database:27017/
    networks:
      - dev-internal

  minio-server:
    container_name: minio-server
    hostname: minio-server
    image: minio/minio:RELEASE.2021-04-22T15-44-28Z.hotfix.e16e75ce3
    networks:
      - dev-internal
    ports:
      - 9000:9000
    volumes:
      - minio-data:/data
    env_file:
      - ./develop.env
    command: server /data
    labels:
      - "traefik.enable=false"
    restart: always

volumes:
  mongodb_data_container:
  minio-data:

networks:
  dev-internal:
    driver: bridge
