openapi: 3.0.0
info:
  title: DanceWithMe
  description: API for the DanceWithMe backend
  version: 1.0.0
#servers:
#  - url: http://api.example.com/v1
#    description: Optional server description, e.g. Main (production) server
#  - url: http://staging-api.example.com
#    description: Optional server description, e.g. Internal staging server for testing
tags:
  - name: event
    description: All methods corresponding to events
  - name: recommendation
paths:
  /event:
    $ref: 'docs/contracts/v1/events.yaml#/eventOperations'

  /event/{eventid}:
    $ref: 'docs/contracts/v1/events.yaml#/eventIdOperations'

  /recommendation?skip=100&take=50:
    $ref: 'docs/contracts/v1/recommendation.yaml#/recommendationOperation'

