openapi: 3.0.0
info:
  title: DanceWithMe
  description: API for the DanceWithMe backend
  version: 1.0.0
servers:
  - url: http://localhost:{port}
    description: local development server
    variables:
      port:
        default: '3000'
#  - url: http://api.example.com/v1
#    description: Optional server description, e.g. Main (production) server
#  - url: http://staging-api.example.com
#    description: Optional server description, e.g. Internal staging server for testing
tags:
  - name: event
    description: All methods corresponding to events
  - name: recommendation
  - name: user
  - name: image
paths:
  /event:
    $ref: 'docs/contracts/v1/events.yaml#/eventOperations'

  /eventsbylocation:
    $ref: 'docs/contracts/v1/events.yaml#/eventByLocationOperations'

  /event/{eventid}:
    $ref: 'docs/contracts/v1/events.yaml#/eventIdOperations'

  /recommendation:
    $ref: 'docs/contracts/v1/recommendation.yaml#/recommendationOperation'

  /user/{userid}:
    $ref: 'docs/contracts/v1/users.yaml#/userIdOperations'

  /image:
    $ref: 'docs/contracts/v1/images.yaml#/uploadImage'

  /image/{imageid}:
    $ref: 'docs/contracts/v1/images.yaml#/getImage'

  /auth/login_redirect/{provider}:
    $ref: 'docs/contracts/v1/auth.yaml#/authProviderRedirect'

  /auth/authorization_code/{provider}:
    $ref: 'docs/contracts/v1/auth.yaml#/submitAuthorizationCode'

  /auth/refresh_token:
    $ref: 'docs/contracts/v1/auth.yaml#/refreshAuth'

  /auth/revoke:
    $ref: 'docs/contracts/v1/auth.yaml#/revokeRefreshToken'

  /auth/force_logout:
    $ref: 'docs/contracts/v1/auth.yaml#/forceLogout'

components:
  securitySchemes:
    tokenAuth:
      type: http
      scheme: bearer
      bearerFormat: PASETO
    refreshAuth:
      type: http
      scheme: bearer
      bearerFormat: string
    fingerprint:
      type: apiKey
      in: cookie
      name: __Secure-fingerprint

security:
  - tokenAuth: []
    fingerprint: []
