module.exports = {
  rules: {
    "array-callback-return": "error",
    "constructor-super": "error",
    "for-direction": "error",
    "getter-return": "error",
    "no-const-assign": "error",
    "no-dupe-keys": "error",
    "no-duplicate-imports": "error",
    "no-fallthrough": "error",
    "no-func-assign": "error",
    "no-import-assign": "error",
    "no-invalid-regexp": "error",
    "no-irregular-whitespace": "error",
    "no-loss-of-precision": "error",
    "no-misleading-character-class": "error",
    "no-new-symbol": "error",
    "no-obj-calls": "error",
    "no-prototype-builtins": "error",
    "no-self-assign": "error",
    "no-self-compare": "error",
    "no-setter-return": "error",
    "no-sparse-arrays": "error",
    "no-this-before-super": "error",
    "no-undef": "error",
    "no-unreachable": "error",
    "no-unmodified-loop-condition": "error",
    "no-unreachable-loop": "error",
    "no-unsafe-finally": "error",
    "no-unsafe-negation": "error",
    "no-unsafe-optional-chaining": "error",
    "no-unused-private-class-members": "error",
    "no-unused-vars": "error",
    "valid-typeof": "error",
    "arrow-body-style": ["error", "as-needed"],
    "no-var": "error",
    "camelcase": "error",
    "capitalized-comments": "error",
    "class-methods-use-this": "error",
    "complexity": ["error", 7],
    "consistent-return": "error",
    "consistent-this": "error",
    "curly": "error",
    "default-case": "error",
    "default-case-last": "error",
    "default-param-last": "error",
    "dot-notation": "error",
    "eqeqeq": "error",
    "func-name-matching": "error",
    "func-style": ["error", "declaration", { "allowArrowFunctions": true }],
    "grouped-accessor-pairs": "error",
    "max-classes-per-file": "error",
    "max-depth": ["error", 4],
    "max-lines": ["error", 300],
    "max-nested-callbacks": ["error", 5],
    "max-params": ["error", 3],
    "new-cap": "error",
    "no-alert": "error",
    "no-array-constructor": "error",
    "no-case-declarations": "error",
    "no-confusing-arrow": "error",
    "no-console": "error",
    "no-continue": "error",
    "no-else-return": "error",
    "no-empty": "error",
    "no-empty-function": "error",
    "no-eq-null": "error",
    "no-eval": "error",
    "no-extend-native": "error",
    "no-lonely-if": "error",
    "no-loop-func": "error",
    "no-magic-numbers": ["error", { "ignore": [0, 1] }],
    "no-new": "error",
    "no-return-assign": "error",
    "no-undefined": "error",
    "no-undef-init": "error",
    "no-unneeded-ternary": "error",
    "no-unused-expressions": "error",
    "no-unused-labels": "error",
    "no-useless-call": "error",
    "no-useless-catch": "error",
    "no-useless-rename": "error",
    "no-useless-return": "error",
    "no-void": "error",
    "prefer-arrow-callback": "error",
    "prefer-const": "error",
    "prefer-destructuring": "error",
    "prefer-object-spread": "error",
    "prefer-promise-reject-errors": "error",
    "prefer-rest-params": "error",
    "prefer-spread": "error",
    "prefer-template": "error",
    "require-await": "error",
    "require-yield": "error",
    "sort-imports": "error",
    "sort-keys": "error",
    "sort-vars": "error",
    "spaced-comment": ["error", "always"],
    "yoda": "error",
    "array-bracket-newline": ["error", "consistent"],
    "array-bracket-spacing": ["error", "never"],
    "brace-style": "error",
    "comma-dangle": "error",
    "comma-spacing": ["error", { "before": false, "after": true }],
    "comma-style": ["error", "last"],
    "func-call-spacing": ["error", "never"],
    "indent": ["error", 2],
    "jsx-quotes": ["error", "prefer-double"],
    "key-spacing": ["error", { "beforeColon": false }],
    "keyword-spacing": ["error", { "before": true }],
    "max-len": ["error", { "code": 160 }],
    "multiline-ternary": ["error", "never"],
    "new-parens": "error",
    "newline-per-chained-call": ["error", { "ignoreChainWithDepth": 2 }],
    "no-extra-parens": "error",
    "no-multi-spaces": "error",
    "no-multiple-empty-lines": ["error", { "max": 1, "maxEOF": 1 }],
    "no-tabs": "error",
    "no-trailing-spaces": "error",
    "no-whitespace-before-property": "error",
    "object-curly-spacing": ["error", "always"],
    "padded-blocks": ["error", "never"],
    "quotes": ["error", "single"],
    "rest-spread-spacing": ["error", "never"],
    "semi": "error",
    "semi-spacing": "error",
    "semi-style": ["error", "last"],
    "space-before-blocks": "error",
    "space-before-function-paren": ["error", {"anonymous": "always", "named": "never", "asyncArrow": "always"}],
    "space-in-parens": ["error", "never"]
  }
};
